Repository CDAT/jupyter-vcdat, pull requests merged in 2019-03, with the labels that each got.

#41 Templates refresh
  src/cell_utils.ts
  src/components/GraphicsMenu.tsx
  src/components/TemplateMenu.tsx
  src/components/VCSMenu.tsx
  src/components/VarMenu.tsx
  src/constants.tsx
  src/index.tsx
  src/notebook_utils.ts
  src/widgets.tsx
Labels: bug, enhancement

#42 Adds the VarMini which is a much smaller version of the VarCard but w…
  setup.py
  src/components/VarMenu.tsx
  src/components/VarMini.tsx
  src/widgets.tsx
Labels: enhancement

#53 Graphics method copy fix
  src/components/VCSMenu.tsx
Labels: bug

#48 Help links
  package.json
  src/CellUtilities.ts
  src/NotebookUtilities.ts
  src/Utilities.tsx
  src/components/DimensionSlider.tsx
  src/components/ExportPlotModal.tsx
  src/components/GraphicsMenu.tsx
  src/components/PlotMenu.tsx
  src/components/TemplateMenu.tsx
  src/components/Tracks.tsx
  src/components/VCSMenu.tsx
  src/components/VarCard.tsx
  src/components/VarLoader.tsx
  src/components/VarMenu.tsx
  src/components/VarMini.tsx
  src/components/Variable.ts
  src/index.tsx
  src/widgets.tsx
Labels: enhancement

#69 Multi file update
  README.md
  src/CellUtilities.ts
  src/NotebookUtilities.ts
  src/Utilities.tsx
  src/components/AxisInfo.tsx
  src/components/DimensionSlider.tsx
  src/components/ExportPlotModal.tsx
  src/components/GraphicsMenu.tsx
  src/components/PlotMenu.tsx
  src/components/TemplateMenu.tsx
  src/components/Tracks.tsx
  src/components/VCSMenu.tsx
  src/components/VarCard.tsx
  src/components/VarLoader.tsx
  src/components/VarMenu.tsx
  src/components/VarMini.tsx
  src/components/Variable.ts
  src/constants.tsx
  src/index.tsx
  src/widgets.tsx
Labels: enhancement

#82 Error handling fixes
  src/NotebookUtilities.ts
  src/Utilities.tsx
  src/components/DimensionSlider.tsx
  src/components/VCSMenu.tsx
  src/components/VarCard.tsx
  src/components/VarLoader.tsx
  src/constants.tsx
  src/widgets.tsx
Labels: bug, enhancement
